version: "3.7"
services:
  optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    environment:
      - TZ=Europe/Stockholm
    network_mode: host

